-- Fix duplicate key constraint error
-- This script handles duplicate records during CSV import

-- Option 1: Delete existing records before import (if you want to replace all data)
-- WARNING: This will delete ALL existing data in the article table
-- DELETE FROM article;

-- Option 2: Check for duplicates and handle them
-- First, let's see what duplicates exist
SELECT "ArtNouvCode", COUNT(*) as duplicate_count
FROM article 
GROUP BY "ArtNouvCode" 
HAVING COUNT(*) > 1
ORDER BY duplicate_count DESC;

-- Option 3: Remove duplicates, keeping only the first occurrence
WITH duplicates AS (
  SELECT id,
         ROW_NUMBER() OVER (PARTITION BY "ArtNouvCode" ORDER BY id) as rn
  FROM article
)
DELETE FROM article 
WHERE id IN (
  SELECT id FROM duplicates WHERE rn > 1
);

-- Option 4: If you want to update existing records instead of inserting duplicates
-- Create a temporary table for your CSV data first, then use UPSERT
-- This is the safest approach for importing new data

-- Step 1: Create temporary table (run this before importing CSV)
CREATE TEMP TABLE article_import (
  "ArtNouvCode" TEXT,
  "ArtDebPer" INTEGER,
  "ArtFinPer" INTEGER,
  "ArtImp" INTEGER,
  "ArtTauxPres" DOUBLE PRECISION,
  "ArtDateDebImp" TIMESTAMP,
  "ArtDateFinImp" TIMESTAMP,
  "ArtMntTaxe" DOUBLE PRECISION,
  "ArtAgentSaisie" TEXT,
  "ArtDateSaisie" TIMESTAMP,
  "ArtRedCode" TEXT,
  "ArtMond" TEXT,
  "ArtOccup" TEXT,
  "ArtArrond" TEXT,
  "ArtRue" TEXT,
  "ArtTexteAdresse" TEXT,
  "ArtSurTot" DOUBLE PRECISION,
  "ArtSurCouv" DOUBLE PRECISION,
  "ArtPrixRef" DOUBLE PRECISION,
  "ArtCatArt" TEXT,
  "ArtQualOccup" TEXT,
  "ArtSurCont" DOUBLE PRECISION,
  "ArtSurDecl" DOUBLE PRECISION,
  "ArtPrixMetre" DOUBLE PRECISION,
  "ArtBaseTaxe" INTEGER,
  "ArtEtat" INTEGER,
  "ArtTaxeOffice" TEXT,
  "ArtNumRole" TEXT,
  "CodeGouv" INTEGER,
  "CodeDeleg" INTEGER,
  "CodeImeda" INTEGER,
  "CodeCom" TEXT,
  "RedTypePrpor" INTEGER,
  "ArtTelDecl" TEXT,
  "ArtEmailDecl" TEXT,
  "ArtCommentaire" TEXT,
  "ArtCatActivite" INTEGER,
  "ArtNomCommerce" TEXT,
  "ArtOccupVoie" INTEGER,
  "ArtLatitude" DOUBLE PRECISION,
  "ArtLongitude" DOUBLE PRECISION,
  "ArtNumDos" TEXT,
  "ArtSourMaj" TEXT,
  "ArtNumMaj" TEXT,
  "ArtDateMaj" TIMESTAMP,
  "ArtSour" TEXT,
  "ArtNumSour" TEXT,
  "ArtDateSour" TIMESTAMP,
  "ArtDateBlocage" TIMESTAMP,
  "ArtTypeTaxe" TEXT,
  "ArtImpFNAH" INTEGER,
  "ArtMntTaxeTib" DOUBLE PRECISION,
  "ArtMntTaxeFnah" DOUBLE PRECISION,
  "ArtAgentCont" TEXT,
  "ArtDateCont" TIMESTAMP,
  "ArtNumAvis" TEXT,
  "ArtVred" TEXT,
  "ArtTypeRue" TEXT,
  "ArtNumRue" TEXT,
  "ArtBis" TEXT,
  "ArtBloc" TEXT,
  "ArtOrdreBloc" TEXT,
  "ArtCodePos" TEXT,
  "ArtSectBur" TEXT,
  "ArtPresNet" TEXT,
  "ArtPresEcl" TEXT,
  "ArtPresCh" TEXT,
  "ArtPresTr" TEXT,
  "ArtPresEauU" TEXT,
  "ArtPresEauP" TEXT,
  "ArtPresAut" TEXT,
  "ArtSurTotCont" DOUBLE PRECISION,
  "ArtSurCouvCont" DOUBLE PRECISION,
  "ArtLoyeeAnn" DOUBLE PRECISION,
  "ArtConstArt" DOUBLE PRECISION,
  "ArtCompArt" DOUBLE PRECISION,
  "ArtUtilArt" DOUBLE PRECISION,
  "ArtTitreFonc" TEXT,
  "ArtValVen" DOUBLE PRECISION,
  "ArtDens" DOUBLE PRECISION,
  "ArtDatePoss" TIMESTAMP,
  "ArtDateImp" TIMESTAMP,
  "ArtSitu" TEXT,
  "ArtFrontNord" DOUBLE PRECISION,
  "ArtFrontSud" DOUBLE PRECISION,
  "ArtFrontEst" DOUBLE PRECISION,
  "ArtFrontOuest" DOUBLE PRECISION,
  "ArtDateEtat" TIMESTAMP,
  "ArtCodeAvTrans" TEXT,
  "ArtCodeApTrans" TEXT,
  "ArtDerAnneeRole" INTEGER,
  "ArtDerAnnee_1Role" INTEGER,
  "ArtCite" TEXT,
  "Artsecteur" TEXT,
  "ArtCellule" TEXT,
  "ArtNomResid" TEXT,
  "ArtNomImmeuble" TEXT,
  "ArtEtage" TEXT,
  "ArtAppart" TEXT,
  "ArtTypeHabit" TEXT,
  "ArtActivSecond" TEXT,
  "ArtEnseigne" TEXT,
  "ArtNomAgent" TEXT,
  "ArtDateRecens" TIMESTAMP,
  "TypeCollect" TEXT,
  "ArtIdMiseAJour" TEXT,
  "ArtDeclCode" TEXT,
  "ArtAgentDecl" TEXT,
  "ArtQualDecl" TEXT
);

-- Step 2: Import your CSV into article_import table
-- (Use Supabase CSV import on the article_import table)

-- Step 3: After importing CSV, run this UPSERT query
INSERT INTO article (
  "ArtNouvCode", "ArtDebPer", "ArtFinPer", "ArtImp", "ArtTauxPres",
  "ArtDateDebImp", "ArtDateFinImp", "ArtMntTaxe", "ArtAgentSaisie", "ArtDateSaisie",
  "ArtRedCode", "ArtMond", "ArtOccup", "ArtArrond", "ArtRue", "ArtTexteAdresse",
  "ArtSurTot", "ArtSurCouv", "ArtPrixRef", "ArtCatArt", "ArtQualOccup",
  "ArtSurCont", "ArtSurDecl", "ArtPrixMetre", "ArtBaseTaxe", "ArtEtat",
  "ArtTaxeOffice", "ArtNumRole", "CodeGouv", "CodeDeleg", "CodeImeda",
  "CodeCom", "RedTypePrpor", "ArtTelDecl", "ArtEmailDecl", "ArtCommentaire",
  "ArtCatActivite", "ArtNomCommerce", "ArtOccupVoie", "ArtLatitude", "ArtLongitude",
  "ArtNumDos", "ArtSourMaj", "ArtNumMaj", "ArtDateMaj", "ArtSour", "ArtNumSour",
  "ArtDateSour", "ArtDateBlocage", "ArtTypeTaxe", "ArtImpFNAH", "ArtMntTaxeTib",
  "ArtMntTaxeFnah", "ArtAgentCont", "ArtDateCont", "ArtNumAvis", "ArtVred",
  "ArtTypeRue", "ArtNumRue", "ArtBis", "ArtBloc", "ArtOrdreBloc", "ArtCodePos",
  "ArtSectBur", "ArtPresNet", "ArtPresEcl", "ArtPresCh", "ArtPresTr",
  "ArtPresEauU", "ArtPresEauP", "ArtPresAut", "ArtSurTotCont", "ArtSurCouvCont",
  "ArtLoyeeAnn", "ArtConstArt", "ArtCompArt", "ArtUtilArt", "ArtTitreFonc",
  "ArtValVen", "ArtDens", "ArtDatePoss", "ArtDateImp", "ArtSitu",
  "ArtFrontNord", "ArtFrontSud", "ArtFrontEst", "ArtFrontOuest", "ArtDateEtat",
  "ArtCodeAvTrans", "ArtCodeApTrans", "ArtDerAnneeRole", "ArtDerAnnee_1Role",
  "ArtCite", "Artsecteur", "ArtCellule", "ArtNomResid", "ArtNomImmeuble",
  "ArtEtage", "ArtAppart", "ArtTypeHabit", "ArtActivSecond", "ArtEnseigne",
  "ArtNomAgent", "ArtDateRecens", "TypeCollect", "ArtIdMiseAJour", "ArtDeclCode",
  "ArtAgentDecl", "ArtQualDecl"
)
SELECT 
  "ArtNouvCode", "ArtDebPer", "ArtFinPer", "ArtImp", "ArtTauxPres",
  "ArtDateDebImp", "ArtDateFinImp", "ArtMntTaxe", "ArtAgentSaisie", "ArtDateSaisie",
  "ArtRedCode", "ArtMond", "ArtOccup", "ArtArrond", "ArtRue", "ArtTexteAdresse",
  "ArtSurTot", "ArtSurCouv", "ArtPrixRef", "ArtCatArt", "ArtQualOccup",
  "ArtSurCont", "ArtSurDecl", "ArtPrixMetre", "ArtBaseTaxe", "ArtEtat",
  "ArtTaxeOffice", "ArtNumRole", "CodeGouv", "CodeDeleg", "CodeImeda",
  "CodeCom", "RedTypePrpor", "ArtTelDecl", "ArtEmailDecl", "ArtCommentaire",
  "ArtCatActivite", "ArtNomCommerce", "ArtOccupVoie", "ArtLatitude", "ArtLongitude",
  "ArtNumDos", "ArtSourMaj", "ArtNumMaj", "ArtDateMaj", "ArtSour", "ArtNumSour",
  "ArtDateSour", "ArtDateBlocage", "ArtTypeTaxe", "ArtImpFNAH", "ArtMntTaxeTib",
  "ArtMntTaxeFnah", "ArtAgentCont", "ArtDateCont", "ArtNumAvis", "ArtVred",
  "ArtTypeRue", "ArtNumRue", "ArtBis", "ArtBloc", "ArtOrdreBloc", "ArtCodePos",
  "ArtSectBur", "ArtPresNet", "ArtPresEcl", "ArtPresCh", "ArtPresTr",
  "ArtPresEauU", "ArtPresEauP", "ArtPresAut", "ArtSurTotCont", "ArtSurCouvCont",
  "ArtLoyeeAnn", "ArtConstArt", "ArtCompArt", "ArtUtilArt", "ArtTitreFonc",
  "ArtValVen", "ArtDens", "ArtDatePoss", "ArtDateImp", "ArtSitu",
  "ArtFrontNord", "ArtFrontSud", "ArtFrontEst", "ArtFrontOuest", "ArtDateEtat",
  "ArtCodeAvTrans", "ArtCodeApTrans", "ArtDerAnneeRole", "ArtDerAnnee_1Role",
  "ArtCite", "Artsecteur", "ArtCellule", "ArtNomResid", "ArtNomImmeuble",
  "ArtEtage", "ArtAppart", "ArtTypeHabit", "ArtActivSecond", "ArtEnseigne",
  "ArtNomAgent", "ArtDateRecens", "TypeCollect", "ArtIdMiseAJour", "ArtDeclCode",
  "ArtAgentDecl", "ArtQualDecl"
FROM article_import
ON CONFLICT ("ArtNouvCode") DO UPDATE SET
  "ArtDebPer" = EXCLUDED."ArtDebPer",
  "ArtFinPer" = EXCLUDED."ArtFinPer",
  "ArtImp" = EXCLUDED."ArtImp",
  "ArtTauxPres" = EXCLUDED."ArtTauxPres",
  "ArtDateDebImp" = EXCLUDED."ArtDateDebImp",
  "ArtDateFinImp" = EXCLUDED."ArtDateFinImp",
  "ArtMntTaxe" = EXCLUDED."ArtMntTaxe",
  "ArtAgentSaisie" = EXCLUDED."ArtAgentSaisie",
  "ArtDateSaisie" = EXCLUDED."ArtDateSaisie",
  "ArtRedCode" = EXCLUDED."ArtRedCode",
  "ArtMond" = EXCLUDED."ArtMond",
  "ArtOccup" = EXCLUDED."ArtOccup",
  "ArtArrond" = EXCLUDED."ArtArrond",
  "ArtRue" = EXCLUDED."ArtRue",
  "ArtTexteAdresse" = EXCLUDED."ArtTexteAdresse",
  "ArtSurTot" = EXCLUDED."ArtSurTot",
  "ArtSurCouv" = EXCLUDED."ArtSurCouv",
  "ArtPrixRef" = EXCLUDED."ArtPrixRef",
  "ArtCatArt" = EXCLUDED."ArtCatArt",
  "ArtQualOccup" = EXCLUDED."ArtQualOccup",
  "ArtSurCont" = EXCLUDED."ArtSurCont",
  "ArtSurDecl" = EXCLUDED."ArtSurDecl",
  "ArtPrixMetre" = EXCLUDED."ArtPrixMetre",
  "ArtBaseTaxe" = EXCLUDED."ArtBaseTaxe",
  "ArtEtat" = EXCLUDED."ArtEtat",
  "ArtTaxeOffice" = EXCLUDED."ArtTaxeOffice",
  "ArtNumRole" = EXCLUDED."ArtNumRole",
  "CodeGouv" = EXCLUDED."CodeGouv",
  "CodeDeleg" = EXCLUDED."CodeDeleg",
  "CodeImeda" = EXCLUDED."CodeImeda",
  "CodeCom" = EXCLUDED."CodeCom",
  "RedTypePrpor" = EXCLUDED."RedTypePrpor",
  "ArtTelDecl" = EXCLUDED."ArtTelDecl",
  "ArtEmailDecl" = EXCLUDED."ArtEmailDecl",
  "ArtCommentaire" = EXCLUDED."ArtCommentaire",
  "ArtCatActivite" = EXCLUDED."ArtCatActivite",
  "ArtNomCommerce" = EXCLUDED."ArtNomCommerce",
  "ArtOccupVoie" = EXCLUDED."ArtOccupVoie",
  "ArtLatitude" = EXCLUDED."ArtLatitude",
  "ArtLongitude" = EXCLUDED."ArtLongitude",
  "ArtNumDos" = EXCLUDED."ArtNumDos",
  "ArtSourMaj" = EXCLUDED."ArtSourMaj",
  "ArtNumMaj" = EXCLUDED."ArtNumMaj",
  "ArtDateMaj" = EXCLUDED."ArtDateMaj",
  "ArtSour" = EXCLUDED."ArtSour",
  "ArtNumSour" = EXCLUDED."ArtNumSour",
  "ArtDateSour" = EXCLUDED."ArtDateSour",
  "ArtDateBlocage" = EXCLUDED."ArtDateBlocage",
  "ArtTypeTaxe" = EXCLUDED."ArtTypeTaxe",
  "ArtImpFNAH" = EXCLUDED."ArtImpFNAH",
  "ArtMntTaxeTib" = EXCLUDED."ArtMntTaxeTib",
  "ArtMntTaxeFnah" = EXCLUDED."ArtMntTaxeFnah",
  "ArtAgentCont" = EXCLUDED."ArtAgentCont",
  "ArtDateCont" = EXCLUDED."ArtDateCont",
  "ArtNumAvis" = EXCLUDED."ArtNumAvis",
  "ArtVred" = EXCLUDED."ArtVred",
  "ArtTypeRue" = EXCLUDED."ArtTypeRue",
  "ArtNumRue" = EXCLUDED."ArtNumRue",
  "ArtBis" = EXCLUDED."ArtBis",
  "ArtBloc" = EXCLUDED."ArtBloc",
  "ArtOrdreBloc" = EXCLUDED."ArtOrdreBloc",
  "ArtCodePos" = EXCLUDED."ArtCodePos",
  "ArtSectBur" = EXCLUDED."ArtSectBur",
  "ArtPresNet" = EXCLUDED."ArtPresNet",
  "ArtPresEcl" = EXCLUDED."ArtPresEcl",
  "ArtPresCh" = EXCLUDED."ArtPresCh",
  "ArtPresTr" = EXCLUDED."ArtPresTr",
  "ArtPresEauU" = EXCLUDED."ArtPresEauU",
  "ArtPresEauP" = EXCLUDED."ArtPresEauP",
  "ArtPresAut" = EXCLUDED."ArtPresAut",
  "ArtSurTotCont" = EXCLUDED."ArtSurTotCont",
  "ArtSurCouvCont" = EXCLUDED."ArtSurCouvCont",
  "ArtLoyeeAnn" = EXCLUDED."ArtLoyeeAnn",
  "ArtConstArt" = EXCLUDED."ArtConstArt",
  "ArtCompArt" = EXCLUDED."ArtCompArt",
  "ArtUtilArt" = EXCLUDED."ArtUtilArt",
  "ArtTitreFonc" = EXCLUDED."ArtTitreFonc",
  "ArtValVen" = EXCLUDED."ArtValVen",
  "ArtDens" = EXCLUDED."ArtDens",
  "ArtDatePoss" = EXCLUDED."ArtDatePoss",
  "ArtDateImp" = EXCLUDED."ArtDateImp",
  "ArtSitu" = EXCLUDED."ArtSitu",
  "ArtFrontNord" = EXCLUDED."ArtFrontNord",
  "ArtFrontSud" = EXCLUDED."ArtFrontSud",
  "ArtFrontEst" = EXCLUDED."ArtFrontEst",
  "ArtFrontOuest" = EXCLUDED."ArtFrontOuest",
  "ArtDateEtat" = EXCLUDED."ArtDateEtat",
  "ArtCodeAvTrans" = EXCLUDED."ArtCodeAvTrans",
  "ArtCodeApTrans" = EXCLUDED."ArtCodeApTrans",
  "ArtDerAnneeRole" = EXCLUDED."ArtDerAnneeRole",
  "ArtDerAnnee_1Role" = EXCLUDED."ArtDerAnnee_1Role",
  "ArtCite" = EXCLUDED."ArtCite",
  "Artsecteur" = EXCLUDED."Artsecteur",
  "ArtCellule" = EXCLUDED."ArtCellule",
  "ArtNomResid" = EXCLUDED."ArtNomResid",
  "ArtNomImmeuble" = EXCLUDED."ArtNomImmeuble",
  "ArtEtage" = EXCLUDED."ArtEtage",
  "ArtAppart" = EXCLUDED."ArtAppart",
  "ArtTypeHabit" = EXCLUDED."ArtTypeHabit",
  "ArtActivSecond" = EXCLUDED."ArtActivSecond",
  "ArtEnseigne" = EXCLUDED."ArtEnseigne",
  "ArtNomAgent" = EXCLUDED."ArtNomAgent",
  "ArtDateRecens" = EXCLUDED."ArtDateRecens",
  "TypeCollect" = EXCLUDED."TypeCollect",
  "ArtIdMiseAJour" = EXCLUDED."ArtIdMiseAJour",
  "ArtDeclCode" = EXCLUDED."ArtDeclCode",
  "ArtAgentDecl" = EXCLUDED."ArtAgentDecl",
  "ArtQualDecl" = EXCLUDED."ArtQualDecl";

-- Step 4: Clean up temporary table
DROP TABLE article_import;

-- Show final results
SELECT COUNT(*) as total_records FROM article;
SELECT 'Import completed successfully!' as status;
