-- Create temporary table with all text columns for CSV import
-- This allows you to import the CSV first, then convert data types

CREATE TEMP TABLE article_temp (
  "ArtNouvCode" TEXT,
  "ArtDebPer" TEXT,
  "ArtFinPer" TEXT,
  "ArtImp" TEXT,
  "ArtTauxPres" TEXT,
  "ArtDateDebImp" TEXT,
  "ArtDateFinImp" TEXT,
  "ArtMntTaxe" TEXT,
  "ArtAgentSaisie" TEXT,
  "ArtDateSaisie" TEXT,
  "ArtRedCode" TEXT,
  "ArtMond" TEXT,
  "ArtOccup" TEXT,
  "ArtArrond" TEXT,
  "ArtRue" TEXT,
  "ArtTexteAdresse" TEXT,
  "ArtSurTot" TEXT,
  "ArtSurCouv" TEXT,
  "ArtPrixRef" TEXT,
  "ArtCatArt" TEXT,
  "ArtQualOccup" TEXT,
  "ArtSurCont" TEXT,
  "ArtSurDecl" TEXT,
  "ArtPrixMetre" TEXT,
  "ArtBaseTaxe" TEXT,
  "ArtEtat" TEXT,
  "ArtTaxeOffice" TEXT,
  "ArtNumRole" TEXT,
  "CodeGouv" TEXT,
  "CodeDeleg" TEXT,
  "CodeImeda" TEXT,
  "CodeCom" TEXT,
  "RedTypePrpor" TEXT,
  "ArtTelDecl" TEXT,
  "ArtEmailDecl" TEXT,
  "ArtCommentaire" TEXT,
  "ArtCatActivite" TEXT,
  "ArtNomCommerce" TEXT,
  "ArtOccupVoie" TEXT,
  "ArtLatitude" TEXT,
  "ArtLongitude" TEXT,
  "ArtNumDos" TEXT,
  "ArtSourMaj" TEXT,
  "ArtNumMaj" TEXT,
  "ArtDateMaj" TEXT,
  "ArtSour" TEXT,
  "ArtNumSour" TEXT,
  "ArtDateSour" TEXT,
  "ArtDateBlocage" TEXT,
  "ArtTypeTaxe" TEXT,
  "ArtImpFNAH" TEXT,
  "ArtMntTaxeTib" TEXT,
  "ArtMntTaxeFnah" TEXT,
  "ArtAgentCont" TEXT,
  "ArtDateCont" TEXT,
  "ArtNumAvis" TEXT,
  "ArtVred" TEXT,
  "ArtTypeRue" TEXT,
  "ArtNumRue" TEXT,
  "ArtBis" TEXT,
  "ArtBloc" TEXT,
  "ArtOrdreBloc" TEXT,
  "ArtCodePos" TEXT,
  "ArtSectBur" TEXT,
  "ArtPresNet" TEXT,
  "ArtPresEcl" TEXT,
  "ArtPresCh" TEXT,
  "ArtPresTr" TEXT,
  "ArtPresEauU" TEXT,
  "ArtPresEauP" TEXT,
  "ArtPresAut" TEXT,
  "ArtSurTotCont" TEXT,
  "ArtSurCouvCont" TEXT,
  "ArtLoyeeAnn" TEXT,
  "ArtConstArt" TEXT,
  "ArtCompArt" TEXT,
  "ArtUtilArt" TEXT,
  "ArtTitreFonc" TEXT,
  "ArtValVen" TEXT,
  "ArtDens" TEXT,
  "ArtDatePoss" TEXT,
  "ArtDateImp" TEXT,
  "ArtSitu" TEXT,
  "ArtFrontNord" TEXT,
  "ArtFrontSud" TEXT,
  "ArtFrontEst" TEXT,
  "ArtFrontOuest" TEXT,
  "ArtDateEtat" TEXT,
  "ArtCodeAvTrans" TEXT,
  "ArtCodeApTrans" TEXT,
  "ArtDerAnneeRole" TEXT,
  "ArtDerAnnee_1Role" TEXT,
  "ArtCite" TEXT,
  "Artsecteur" TEXT,
  "ArtCellule" TEXT,
  "ArtNomResid" TEXT,
  "ArtNomImmeuble" TEXT,
  "ArtEtage" TEXT,
  "ArtAppart" TEXT,
  "ArtTypeHabit" TEXT,
  "ArtActivSecond" TEXT,
  "ArtEnseigne" TEXT,
  "ArtNomAgent" TEXT,
  "ArtDateRecens" TEXT,
  "TypeCollect" TEXT,
  "ArtIdMiseAJour" TEXT,
  "ArtDeclCode" TEXT,
  "ArtAgentDecl" TEXT,
  "ArtQualDecl" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- After importing CSV into article_temp, run this to convert and insert into main table:

INSERT INTO article (
  "ArtNouvCode", "ArtDebPer", "ArtFinPer", "ArtImp", "ArtTauxPres",
  "ArtDateDebImp", "ArtDateFinImp", "ArtMntTaxe", "ArtAgentSaisie", "ArtDateSaisie",
  "ArtRedCode", "ArtMond", "ArtOccup", "ArtArrond", "ArtRue", "ArtTexteAdresse",
  "ArtSurTot", "ArtSurCouv", "ArtPrixRef", "ArtCatArt", "ArtQualOccup",
  "ArtSurCont", "ArtSurDecl", "ArtPrixMetre", "ArtBaseTaxe", "ArtEtat",
  "ArtTaxeOffice", "ArtNumRole", "CodeGouv", "CodeDeleg", "CodeImeda",
  "CodeCom", "RedTypePrpor", "ArtTelDecl", "ArtEmailDecl", "ArtCommentaire",
  "ArtCatActivite", "ArtNomCommerce", "ArtOccupVoie", "ArtLatitude", "ArtLongitude",
  "ArtNumDos", "ArtSourMaj", "ArtNumMaj", "ArtDateMaj", "ArtSour", "ArtNumSour",
  "ArtDateSour", "ArtDateBlocage", "ArtTypeTaxe", "ArtImpFNAH", "ArtMntTaxeTib",
  "ArtMntTaxeFnah", "ArtAgentCont", "ArtDateCont", "ArtNumAvis", "ArtVred",
  "ArtTypeRue", "ArtNumRue", "ArtBis", "ArtBloc", "ArtOrdreBloc", "ArtCodePos",
  "ArtSectBur", "ArtPresNet", "ArtPresEcl", "ArtPresCh", "ArtPresTr",
  "ArtPresEauU", "ArtPresEauP", "ArtPresAut", "ArtSurTotCont", "ArtSurCouvCont",
  "ArtLoyeeAnn", "ArtConstArt", "ArtCompArt", "ArtUtilArt", "ArtTitreFonc",
  "ArtValVen", "ArtDens", "ArtDatePoss", "ArtDateImp", "ArtSitu",
  "ArtFrontNord", "ArtFrontSud", "ArtFrontEst", "ArtFrontOuest", "ArtDateEtat",
  "ArtCodeAvTrans", "ArtCodeApTrans", "ArtDerAnneeRole", "ArtDerAnnee_1Role",
  "ArtCite", "Artsecteur", "ArtCellule", "ArtNomResid", "ArtNomImmeuble",
  "ArtEtage", "ArtAppart", "ArtTypeHabit", "ArtActivSecond", "ArtEnseigne",
  "ArtNomAgent", "ArtDateRecens", "TypeCollect", "ArtIdMiseAJour", "ArtDeclCode",
  "ArtAgentDecl", "ArtQualDecl", "created_at", "updated_at"
)
SELECT 
  "ArtNouvCode",
  CASE WHEN "ArtDebPer" = 'NULL' OR "ArtDebPer" = '' THEN NULL ELSE "ArtDebPer"::INTEGER END,
  CASE WHEN "ArtFinPer" = 'NULL' OR "ArtFinPer" = '' THEN NULL ELSE "ArtFinPer"::INTEGER END,
  CASE WHEN "ArtImp" = 'NULL' OR "ArtImp" = '' THEN NULL ELSE "ArtImp"::INTEGER END,
  CASE WHEN "ArtTauxPres" = 'NULL' OR "ArtTauxPres" = '' THEN NULL ELSE "ArtTauxPres"::DOUBLE PRECISION END,
  CASE WHEN "ArtDateDebImp" = 'NULL' OR "ArtDateDebImp" = '' THEN NULL ELSE "ArtDateDebImp"::TIMESTAMP END,
  CASE WHEN "ArtDateFinImp" = 'NULL' OR "ArtDateFinImp" = '' THEN NULL ELSE "ArtDateFinImp"::TIMESTAMP END,
  CASE WHEN "ArtMntTaxe" = 'NULL' OR "ArtMntTaxe" = '' THEN NULL ELSE "ArtMntTaxe"::DOUBLE PRECISION END,
  "ArtAgentSaisie",
  CASE WHEN "ArtDateSaisie" = 'NULL' OR "ArtDateSaisie" = '' THEN NULL ELSE "ArtDateSaisie"::TIMESTAMP END,
  "ArtRedCode", "ArtMond", "ArtOccup", "ArtArrond", "ArtRue", "ArtTexteAdresse",
  CASE WHEN "ArtSurTot" = 'NULL' OR "ArtSurTot" = '' THEN NULL ELSE "ArtSurTot"::DOUBLE PRECISION END,
  CASE WHEN "ArtSurCouv" = 'NULL' OR "ArtSurCouv" = '' THEN NULL ELSE "ArtSurCouv"::DOUBLE PRECISION END,
  CASE WHEN "ArtPrixRef" = 'NULL' OR "ArtPrixRef" = '' THEN NULL ELSE "ArtPrixRef"::DOUBLE PRECISION END,
  "ArtCatArt", "ArtQualOccup",
  CASE WHEN "ArtSurCont" = 'NULL' OR "ArtSurCont" = '' THEN NULL ELSE "ArtSurCont"::DOUBLE PRECISION END,
  CASE WHEN "ArtSurDecl" = 'NULL' OR "ArtSurDecl" = '' THEN NULL ELSE "ArtSurDecl"::DOUBLE PRECISION END,
  CASE WHEN "ArtPrixMetre" = 'NULL' OR "ArtPrixMetre" = '' THEN NULL ELSE "ArtPrixMetre"::DOUBLE PRECISION END,
  CASE WHEN "ArtBaseTaxe" = 'NULL' OR "ArtBaseTaxe" = '' THEN NULL ELSE "ArtBaseTaxe"::INTEGER END,
  CASE WHEN "ArtEtat" = 'NULL' OR "ArtEtat" = '' THEN NULL ELSE "ArtEtat"::INTEGER END,
  "ArtTaxeOffice", "ArtNumRole",
  CASE WHEN "CodeGouv" = 'NULL' OR "CodeGouv" = '' THEN NULL ELSE "CodeGouv"::INTEGER END,
  CASE WHEN "CodeDeleg" = 'NULL' OR "CodeDeleg" = '' THEN NULL ELSE "CodeDeleg"::INTEGER END,
  CASE WHEN "CodeImeda" = 'NULL' OR "CodeImeda" = '' THEN NULL ELSE "CodeImeda"::INTEGER END,
  "CodeCom",
  CASE WHEN "RedTypePrpor" = 'NULL' OR "RedTypePrpor" = '' THEN NULL ELSE "RedTypePrpor"::INTEGER END,
  "ArtTelDecl", "ArtEmailDecl", "ArtCommentaire",
  CASE WHEN "ArtCatActivite" = 'NULL' OR "ArtCatActivite" = '' THEN NULL ELSE "ArtCatActivite"::INTEGER END,
  "ArtNomCommerce",
  CASE WHEN "ArtOccupVoie" = 'NULL' OR "ArtOccupVoie" = '' THEN NULL ELSE "ArtOccupVoie"::INTEGER END,
  CASE WHEN "ArtLatitude" = 'NULL' OR "ArtLatitude" = '' THEN NULL ELSE "ArtLatitude"::DOUBLE PRECISION END,
  CASE WHEN "ArtLongitude" = 'NULL' OR "ArtLongitude" = '' THEN NULL ELSE "ArtLongitude"::DOUBLE PRECISION END,
  "ArtNumDos", "ArtSourMaj", "ArtNumMaj",
  CASE WHEN "ArtDateMaj" = 'NULL' OR "ArtDateMaj" = '' THEN NULL ELSE "ArtDateMaj"::TIMESTAMP END,
  "ArtSour", "ArtNumSour",
  CASE WHEN "ArtDateSour" = 'NULL' OR "ArtDateSour" = '' THEN NULL ELSE "ArtDateSour"::TIMESTAMP END,
  CASE WHEN "ArtDateBlocage" = 'NULL' OR "ArtDateBlocage" = '' THEN NULL ELSE "ArtDateBlocage"::TIMESTAMP END,
  "ArtTypeTaxe", "ArtImpFNAH", "ArtMntTaxeTib", "ArtMntTaxeFnah", "ArtAgentCont",
  CASE WHEN "ArtDateCont" = 'NULL' OR "ArtDateCont" = '' THEN NULL ELSE "ArtDateCont"::TIMESTAMP END,
  "ArtNumAvis", "ArtVred", "ArtTypeRue", "ArtNumRue", "ArtBis", "ArtBloc", "ArtOrdreBloc", "ArtCodePos",
  "ArtSectBur", "ArtPresNet", "ArtPresEcl", "ArtPresCh", "ArtPresTr", "ArtPresEauU", "ArtPresEauP", "ArtPresAut",
  "ArtSurTotCont", "ArtSurCouvCont", "ArtLoyeeAnn", "ArtConstArt", "ArtCompArt", "ArtUtilArt", "ArtTitreFonc",
  "ArtValVen", "ArtDens",
  CASE WHEN "ArtDatePoss" = 'NULL' OR "ArtDatePoss" = '' THEN NULL ELSE "ArtDatePoss"::TIMESTAMP END,
  CASE WHEN "ArtDateImp" = 'NULL' OR "ArtDateImp" = '' THEN NULL ELSE "ArtDateImp"::TIMESTAMP END,
  "ArtSitu", "ArtFrontNord", "ArtFrontSud", "ArtFrontEst", "ArtFrontOuest",
  CASE WHEN "ArtDateEtat" = 'NULL' OR "ArtDateEtat" = '' THEN NULL ELSE "ArtDateEtat"::TIMESTAMP END,
  "ArtCodeAvTrans", "ArtCodeApTrans", "ArtDerAnneeRole", "ArtDerAnnee_1Role", "ArtCite", "Artsecteur", "ArtCellule",
  "ArtNomResid", "ArtNomImmeuble", "ArtEtage", "ArtAppart", "ArtTypeHabit", "ArtActivSecond", "ArtEnseigne",
  "ArtNomAgent",
  CASE WHEN "ArtDateRecens" = 'NULL' OR "ArtDateRecens" = '' THEN NULL ELSE "ArtDateRecens"::TIMESTAMP END,
  "TypeCollect", "ArtIdMiseAJour", "ArtDeclCode", "ArtAgentDecl", "ArtQualDecl",
  CASE WHEN "created_at" = 'NULL' OR "created_at" = '' THEN NULL ELSE "created_at"::TIMESTAMP END,
  CASE WHEN "updated_at" = 'NULL' OR "updated_at" = '' THEN NULL ELSE "updated_at"::TIMESTAMP END
FROM article_temp;

-- Clean up temporary table
DROP TABLE article_temp;
